### ISSUE TITLE
Valvs_setup_reads might not get all files.

### ISSUE THREAD

**Issue by ZackBoyd123** [ZackBoyd123/valvs#30]
in these line of code
``` bash
if [ -z $OPT_1 ]
then
	ls *_R1_*.f*q *_R1.f*q *_1.f*q > filelist.txt 2>/dev/null
```   
If the user had files ``my_data1.fq`` & ``my_data2.fq`` the script will think they are using unpaired reads.   
Maybe user should be warned if their data doesn't end in what is specified in the code?

**Comment by rjorton** [comment]
Duplicate issue.

Can't do anytine about my_data1.fq my_data2.fq - as illumina files end in 001.fastq by default.

Added in *_1.*fq and *_1_*.f*q
